azkv more unittest coverage
external-secrets/external-secrets pull request #1149
Opened 2022-05-16 13:19 UTC by dreadful-dragon

Unit Tests added to have more coverage in the azure Keyvault
Specifically testing to validate the store

2022-05-20 08:15 UTC, moolen commented
Hey @dre, can you refactor this test a bit so the new test cases fit into the table?

2022-05-24 13:39 UTC, dreadful-dragon commented
> Hey @dreadful-dragon can you refactor this test a bit so the new test cases fit into the table?

Hello @moolen, what do you mean? Which table?

2022-05-24 13:39 UTC, dreadful-dragon commented
> Hey @dreadful-dragon can you refactor this test a bit so the new test cases fit into the table?

Hello @moolen, what do you mean? Which table?

2022-06-03 18:24 UTC, moolen requested changes
Hey, sorry for taking such a long time to get back to you :bow:
The test table can be simplified when changing the type, see comment. Can you change that, please? :pray:

2022-06-03 18:24 UTC, moolen commented on pkg/provider/azure/keyvault/keyvault_test.go
>  		auth esv1beta1.AzureKVAuth
If you change the type signature here to `*esv1beta1.SecretStore` you can define one individual SecretStore per test case and avoid the complexity

2022-06-10 20:08 UTC, moolen commented
/approve

2022-06-10 20:09 UTC, moolen commented
/merge

2022-06-10 20:09 UTC, moolen approved these changes

2022-06-10 20:10 UTC, merged