Add gcpsm provider
external-secrets/external-secrets pull request #144
Opened 2021-05-11 09:54 UTC by gabibeyer

Fix merge conflicts for the GCP Secret Manager provider

2021-05-12 07:51 UTC, jonatasbaldin requested changes
Hi there, thanks for the awesome work ✨ 

On all the error checking, you could follow some good practices:
- Define the custom error messages as constants, like in `pkg/provider/aws/provider.go`
- Not call `log` since the error logging is already done on `externalsecret_controller.go`
- Always include the original `err` message on the `return` statement

Would be also nice to have a couple of unit tests for this, like on AWS and Vault.

Also left a comment on the code itself.

Again, thanks a bunch 💃

2021-05-12 07:51 UTC, jonatasbaldin commented on pkg/provider/gcp/secretmanager/secretsmanager.go
> +func (sm *GCP) GetSecretMap(ctx context.Context, ref esv1alpha1.ExternalSecretDataRemoteRef) (map[string][]byte, error) {
Is the `GetSecretMap` not possible today with GCP SM or will this still be implemented?

2021-05-12 08:39 UTC, gabibeyer commented
Hey @jonatasbaldin Thank you so much for the input! I completely forgot to set this PR as a `draft` :woman_facepalming. I will implement the best practices for error checking, add unit tests and look into the `GetSecretsMap`. Thank you again for the input!

2021-05-12 09:30 UTC, jonatasbaldin commented
No worries, thanks again for the PR ❤️

__________________________

Jonatas Baldin

Blog <https://deployeveryday.com/> | GitHub
<https://github.com/jonatasbaldin> | Twitter
<https://twitter.com/jonatasbaldin>




On Wed, May 12, 2021 at 10:39 AM Gabi Beyer ***@***.***>
wrote:

> Hey @jonatasbaldin <https://github.com/jonatasbaldin> Thank you so much
> for the input! I completely forgot to set this PR as a draft
> :woman_facepalming. I will implement the best practices for error checking,
> add unit tests and look into the GetSecretsMap. Thank you again for the
> input!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/external-secrets/external-secrets/pull/144#issuecomment-839584575>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBML7GJAU3KAWG57KB3ZLTTNI5ENANCNFSM44U6Q7SA>
> .
>

2021-05-18 11:08 UTC, knelasevero commented
@moolen @jonatasbaldin @mcavoyk any of you have any idea why check-diff is failing here? Seems to be fine locally :thinking:

2021-05-18 16:43 UTC, mcavoyk commented
> any of you have any idea why check-diff is failing here? Seems to be fine locally

Running locally I see a diff in `go.mod`. I agree though that CI step is a bit of a black box, created small change to print diff on failure here https://github.com/external-secrets/external-secrets/pull/157

2021-05-18 17:29 UTC, knelasevero commented
Thanks @mcavoyk :) 

@gabibeyer try rebasing and seeing the error on ci

2021-05-19 21:06 UTC, knelasevero commented
/approve

2021-05-27 10:46 UTC, knelasevero commented
Already tested this! :smile: Great work @gabibeyer @1aziz

2021-05-27 10:47 UTC, knelasevero commented
/giphy party

2021-05-27 10:47 UTC, knelasevero commented
/merge

2021-05-27 10:48 UTC, merged