Refactor parameterstore unit test
external-secrets/external-secrets pull request #164
Opened 2021-05-21 16:17 UTC by leewei05

- refactor `parameterstore_test.go`, I try to follow the style with `secretsmanager_test.go` to keep it consistent
- ignore vim swp files 😁

2021-05-27 06:38 UTC, moolen requested changes
Hey @leewei05, sorry it took some time reviewing this one.
Looks good overall thank you for this PR! I found an issue in `TestGetSecret`, see comments below.

2021-05-27 06:38 UTC, moolen commented on pkg/provider/aws/parameterstore/parameterstore_test.go
> +		if cmp.Equal(out, v.expectedData) {
this should be `v.expectedSecret`. `expectedData` isn't used in this test case and is always `nil`.

2021-05-27 06:38 UTC, moolen commented on pkg/provider/aws/parameterstore/parameterstore_test.go
> +		pstc.expectedSecret = "bang"
What's missing here is:
```go
pstc.remoteRef.Property = "/shmoo"
```

once this is in and `expectedSecret` is being used below the coverage & functionality should be the same as before!

2021-05-27 11:47 UTC, leewei05 commented
@moolen hmm, just fixed the test case, but it seems like the test coverage still couldn't pass. Should I try to rebase this with main branch and try again? 🤔

2021-05-27 15:26 UTC, knelasevero commented
> hmm, just fixed the test case, but it seems like the test coverage still couldn't pass. Should I try to rebase this with main branch and try again?

I would not worry that much about the codecov report. Codecov is being a bit agressive on the analysis. We need to make it a bit more forgiving.

2021-05-28 05:15 UTC, moolen approved these changes
LGTM, Thanks you!
Indeed, codecoverage is a bit odd sometimes :/

2021-05-28 05:15 UTC, moolen commented
/merge

2021-05-28 05:16 UTC, moolen commented
/approve

2021-05-28 05:16 UTC, moolen commented
/merge

2021-05-28 05:17 UTC, merged