feat: attach sbom/provenance files to GH release, fix clomonitor
external-secrets/external-secrets pull request #1656
Opened 2022-10-22 07:42 UTC by moolen

This PR attaches sbom and provenance files to GH release assets.
Further, it fixes a couple of minor clomonitor issues, see https://clomonitor.io/projects/cncf/external-secrets:
* maintainers
* roadmap
* sbom
* signed releases
* license scanning

### Proof of work
https://github.com/moolen/external-secrets/releases/tag/v0.6.1-rc3

2022-10-23 03:04 UTC, IdanAdar requested changes
Looks like we're missing the `maintainers` team?

2022-10-25 11:46 UTC, moolen commented
I've added the @external-secrets/maintainers team recently ([mgmt deeplink](https://github.com/orgs/external-secrets/teams/maintainers)) or are you referring to something else?

2022-10-25 21:26 UTC, moolen commented
I just found the issue @IdanAdar, the team `@external-secrets/maintainers` didn't have explicit access to this repository. This has been fixed now.

2022-10-27 06:24 UTC, IdanAdar approved these changes

2022-10-27 06:59 UTC, merged