Validator
external-secrets/external-secrets pull request #2929
Opened 2023-12-05 16:31 UTC by Mehrbod2002

## Problem Statement

Fix duplicates keys .

## Related Issue

Fixes #2921 

## Checklist

- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [x ] My changes have reasonable test coverage
- [ x] All tests pass with `make test`
- [ x] I ensured my PR is ready for review with `make reviewable`

2023-12-05 22:53 UTC, shuheiktgw requested changes
Thanks for your contribution, @Mehrbod2002! I left one comment, but overall it looks good to me. The DCO job fails so please take a look at [the detail ](https://github.com/external-secrets/external-secrets/pull/2929/checks?check_run_id=19336986032)and resolve it by signing the commits off.

2023-12-05 22:53 UTC, shuheiktgw commented on apis/externalsecrets/v1beta1/externalsecret_validator.go
> +	seenKeys := make(map[string]bool)
nit, we usually use `map[string]struct{}` to express a set in Go

2023-12-05 23:54 UTC, shuheiktgw commented
https://github.com/external-secrets/external-secrets/issues/2921#issuecomment-1839411106
Would you take a look at the PR as well, @gusfcarvalho? Thanks!

2023-12-06 19:25 UTC, Mehrbod2002 commented
What do you think ? @shuheiktgw

2023-12-10 16:31 UTC, Mehrbod2002 commented
@shuheiktgw I think we should better close it .

2023-12-10 23:51 UTC, shuheiktgw commented
Waiting for https://github.com/external-secrets/external-secrets/pull/2929#issuecomment-1841823953

2023-12-11 07:48 UTC, gusfcarvalho commented
Sorry for the delay! This logic would not work for many use cases with creationPolicy=Merge and DeletionPolicy=Merge/Delete, where users effectively leverage the duplicate keys to create `default/overlay` configuration.

this logic should only be applied to DeletionPolicy=Retain in order for it to be accurate.

2023-12-16 16:00 UTC, Mehrbod2002 commented
@shuheiktgw  @gusfcarvalho can you review it ?

2023-12-18 16:10 UTC, Mehrbod2002 commented
@shuheiktgw  @gusfcarvalho can you review it ?

2023-12-21 22:44 UTC, shuheiktgw commented
Thanks, @gusfcarvalho, and I'm sorry I cannot review this PR for a while. I have been considering other edge cases if the SecretKey could be duplicated. For example, if users use the CreationPolicy = Merge, it could be duplicated. Also, some providers support the property field, and IIUC, the key could be duplicated as well in that case. Considering those complexities, I have to disagree with setting validation there. There is too little to gain here... If you have any objections, please feel free to reopen it, but I'm closing this PR for now 🙇

2023-12-21 22:44 UTC, closed without merging

2024-01-04 08:11 UTC, Dgadavin commented
@shuheiktgw Good day. I agree that SecretKey could be duplicated but the logic is not clear. As I mentioned in issue that I opened when you add two SecretKey with different values it takes the last one without any log message or k8s event or other things that can help you to debug. And in real life(production) this can create a real troubels.

2024-01-05 08:24 UTC, shuheiktgw commented
Hi @Dgadavin, thanks for pointing it out! Hmm, now that I read my comment above again, I feel something is off. I may have mixed up PushSecret with ExternalSecret at that time... I cannot reopen this PR since the original branch has been deleted, but let me cherry-pick the commits and create a new PR 🙇  @Mehrbod2002

2024-01-05 11:36 UTC, Mehrbod2002 commented
@shuheiktgw Can i rewrite in new PR ?

2024-01-07 01:15 UTC, shuheiktgw commented
That would be great. Thank you! @Mehrbod2002