Feat/add validations to external secret data from remote ref
external-secrets/external-secrets pull request #2962
Opened 2023-12-18 20:59 UTC by LucasPimentel123

## Problem Statement

Currently, there are no validations on the ExternalSecretDataFromRemoteRef, but it should
- set either Find, Exact, or SourceRef & SourceRef.GeneratorRef.
- set SourceRef.GeneratorRef if we want to use SourceRef.

## Related Issue

Fixes #2916 

## Proposed Changes

I added the validations on the validateExternalSecret function

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

2023-12-21 23:34 UTC, shuheiktgw requested changes
I've left some comments, so please take a look at them!

2023-12-21 23:34 UTC, shuheiktgw commented on apis/externalsecrets/v1beta1/externalsecret_validator.go
> +		if !findOrExtract && (ref.SourceRef != nil ||  ref.SourceRef.GeneratorRef != nil) {
This condition seems to be wrong. It should be  

```
!findOrExtract && (ref.SourceRef == nil || ref.SourceRef.GeneratorRef == nil)
```

Also, I found that `!findOrExtract` is hard to understand. Why don't we just use the following condition?

```
ref.Find == nil && ref.Extract == nil && (ref.SourceRef == nil || ref.SourceRef.GeneratorRef == nil)
```

2023-12-21 23:34 UTC, shuheiktgw commented on apis/externalsecrets/v1beta1/externalsecret_validator.go
> +		if !findOrExtract && (ref.SourceRef != nil ||  ref.SourceRef.GeneratorRef != nil) {
Would you add test cases to cover the four cases?

2023-12-21 23:34 UTC, shuheiktgw commented on apis/externalsecrets/v1beta1/externalsecret_validator.go
> +			errs = errors.Join(errs, fmt.Errorf("either find, extract or source and generator must be set"))
```suggestion
			errs = errors.Join(errs, fmt.Errorf("either extract, find, or sourceRef with generatorRef must be set to dataFrom"))
```

2023-12-21 23:34 UTC, shuheiktgw commented on apis/externalsecrets/v1beta1/externalsecret_validator.go
> +			errs = errors.Join(errs, fmt.Errorf("generator must be set if SourceRef is used"))
```suggestion
			errs = errors.Join(errs, fmt.Errorf("generatorRef cannot be empty when using sourceRef in dataFrom"))
```

2024-02-06 23:18 UTC, shuheiktgw commented
Hi @LucasPimentel123 👋 Are you still working on this PR?

2024-04-18 16:28 UTC, gusfcarvalho commented
Hi @LucasPimentel123 ! Are you still working on this PR?

2024-04-20 00:48 UTC, shuheiktgw commented
I will take it over from here

2024-04-20 02:22 UTC, shuheiktgw commented
Closing in favor of https://github.com/external-secrets/external-secrets/pull/3390

2024-04-20 02:22 UTC, closed without merging