added metrics support for akeyless
external-secrets/external-secrets pull request #3069
Opened 2024-01-22 23:39 UTC by charan986

## Problem Statement

What is the problem you're trying to solve?

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

2024-01-23 13:48 UTC, charan986 commented
@renanaAkeyless - Can you please this review this PR as well?

2024-01-24 13:39 UTC, charan986 commented
Hi @rogertuma , can you please the PR?

2024-01-24 19:57 UTC, moolen requested changes
Hey @charan986 thank you for your PR! I left some comments below.
Unfortunately the linter can't catch the issues of unused variables.

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSPSGetParametersByPath   = "GetParametersByPath"
this isn't used

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSSMDescribeSecret        = "DescribeSecret"
The REST API call is `DescribeItem`, i'd suggest to call it that as well to avoid confusion

2024-01-24 19:57 UTC, moolen commented on pkg/provider/akeyless/akeyless_api.go
> +	metrics.ObserveAPICall(constants.ProviderAKEYLESSSM, constants.CallAKEYLESSSMDescribeSecret, err)
This `.ObserveAPICall()` is being called twice: once inside `a.DescribeItem()` and right here. I'd suggest to remove it here and just call it in `DescribeItem()`.

2024-01-24 19:57 UTC, moolen commented on pkg/provider/akeyless/akeyless_api.go
The `RestAPI.Auth(ctx)` in line `:70` is not being observed, i suggest to add a `ObserveAPICall()` there, too

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSSMDeleteSecret          = "DeleteSecret"
This isn't used

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSSMCreateSecret          = "CreateSecret"
This isn't used

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSSMPutSecretValue        = "PutSecretValue"
This isn't used

2024-01-24 19:57 UTC, moolen commented on pkg/constants/constants.go
> +	CallAKEYLESSSMGenerateSAToken       = "GenerateServiceAccountToken"
This isn't used

2024-01-24 21:34 UTC, moolen approved these changes
LGTM, thank you for your contribution :bow:

2024-01-24 21:34 UTC, merged