Implementation of Chef External Secrets Provider
external-secrets/external-secrets pull request #3073
Opened 2024-01-24 09:55 UTC by sourav977

## Problem Statement

Introducing Chef External Secrets Provider. 
This will enable users to seamlessly integrate Chef-based secret management with Kubernetes through the existing External Secrets framework.

## Related Issue

issue: https://github.com/external-secrets/external-secrets/issues/2905

## Related work
- documentation: docs/provider/chef.md
- api: apis/externalsecrets/v1beta1/secretstore_chef_types.go
- implementation: pkg/provider/chef

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

2024-01-31 13:14 UTC, Skarlso commented on apis/externalsecrets/v1beta1/secretstore_chef_types.go
> +	ServerURL string `json:"serverurl"`
```suggestion
	ServerURL string `json:"serverUrl"`
```

or

```suggestion
	ServerURL string `json:"serverURL"`
```

2024-01-31 13:39 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	errMisingStoreSpec                       = "missing store spec"
```suggestion
	errMissingStoreSpec                       = "missing store spec"
```

2024-01-31 13:41 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	}
```suggestion
	if err := kube.Get(ctx, objectKey, credentialsSecret); err != nil {
		return nil, fmt.Errorf(errFetchK8sSecret, err)
	}
```

2024-01-31 13:45 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	if (secretKey == nil) || (len(secretKey) == 0) {
```suggestion
	if len(secretKey) == 0 {
```

len already does nil check

2024-01-31 13:54 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	metrics.ObserveAPICall(ProviderChef, CallChefListDataBagItems, err)
I think we would want this metric even if it failed in the first `IsNil` call, right?

2024-01-31 13:57 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +// Retrives all DatabagItems of a Databag.
```suggestion
```

2024-01-31 13:59 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	metrics.ObserveAPICall(ProviderChef, CallChefGetDataBagItem, err)
put this on the first line

2024-01-31 14:04 UTC, Skarlso commented on pkg/provider/chef/chef.go
> +	metrics.ObserveAPICall(ProviderChef, CallChefListDataBagItems, err)
I understand that it logs the error, but this metric will no longer be available if chef is uninitialized.

Meh, maybe, this is fine. :D

2024-01-31 14:10 UTC, Skarlso requested changes
Generally looks okay. The branch needs a `go mod tidy` and a signed commit. :)

2024-02-07 16:11 UTC, sourav977 commented
The missed unsigned commits have been signed by me and my teammates but DCO check now complaining about other commits . @Skarlso Could you help me in resolving DCO check issue ?

2024-02-09 07:12 UTC, sourav977 commented
@Skarlso @sebagomez 
> Alternatively, take the diff, and create another PR and start off fresh if squashing is too complicated.

As suggested, we are closing this PR as we are unable to resolve unsigned commits , latest PR: https://github.com/external-secrets/external-secrets/pull/3127

2024-02-09 07:12 UTC, closed without merging